vim.loader.enable()

require 'startup.local'
require 'startup.base'
require 'startup.minpac'
require 'startup.lightline'
require 'startup.oscyank'
require 'startup.toggle_quickfix'
require 'startup.treesitter'
require 'startup.indent_blankline'
require 'startup.lsp'
require 'startup.sayonara'
require 'startup.gin'
require 'startup.suda'
require 'startup.skkeleton'
require 'startup.ddc'
require 'startup.ddu'
