[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'rbtnn/vim-ambiwidth'

[[plugins]]
repo = 'cocopon/vaffle.vim'
depends = ['vim-devicons']

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'nvim-treesitter/playground'

[[plugins]]
repo = 'Shougo/pum.vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'ojroques/vim-oscyank'

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'cocopon/pgmnt.vim'

[[plugins]]
repo = 'yash268925/iceberg.vim'
rev = 'feat/treesitter-rules'

[[plugins]]
repo = 'drmingdrmer/vim-toggle-quickfix'

[[plugins]]
repo = 'matsui54/denops-popup-preview.vim'
depends = ['denops.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-scripts/Decho'

[[plugins]]
repo = 'lambdalisue/suda.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = 'denops.vim'

# ddc-ui
[[plugins]]
repo = 'Shougo/ddc-ui-pum'
depends = ['denops.vim', 'ddc.vim', 'pum.vim']

# ddc-matcher
[[plugins]]
repo = 'tani/ddc-fuzzy'

# ddc-sorter
[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

# ddc-source
[[plugins]]
repo = 'LumaKernel/ddc-source-file'

[[plugins]]
repo = 'tani/ddc-path'

[[plugins]]
repo = 'Shougo/ddc-source-nvim-lsp'
depends = ['nvim-lspconfig']

[[plugins]]
repo = 'Shougo/ddc-source-cmdline'

[[plugins]]
repo = 'Shougo/ddc-source-cmdline-history'

[[plugins]]
repo = 'Shougo/ddc-source-rg'
