[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'
hook_source = '''
  lua require('impatient')
'''

[[plugins]]
repo = 'cocopon/vaffle.vim'
depends = ['vim-devicons']
on_event = 'VimEnter'
hook_add = '''
  let g:vaffle_render_custom_icon = 'VaffleRenderCustomIcon'
  let NERDTreeHijackNetrw = 0

  function! VaffleRenderCustomIcon(item)
    return WebDevIconsGetFileTypeSymbol(a:item.basename, a:item.is_dir)
  endfunction
'''
