[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lewis6991/impatient.nvim'
if = 'has("nvim")'

[[plugins]]
repo = 'vim-denops/denops.vim'
hook_add = '''
  let g:denops_server_addr = '127.0.0.1:32123'
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'cocopon/vaffle.vim'
depends = ['vim-devicons']
hook_add = '''
  let g:vaffle_render_custom_icon = 'VaffleRenderCustomIcon'
  let NERDTreeHijackNetrw = 0

  function! VaffleRenderCustomIcon(item)
    return WebDevIconsGetFileTypeSymbol(a:item.basename, a:item.is_dir)
  endfunction

  call LoadSubscript('init/vaffle.vim')
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_post_update = 'TSUpdate'

[[plugins]]
repo = 'nvim-treesitter/playground'

[[plugins]]
repo = 'Shougo/pum.vim'
depends = ['ddc.vim']
hook_add = '''
  call LoadSubscript('init/pum.vim')
'''

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'lambdalisue/guise.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'ojroques/vim-oscyank'
hook_add = '''
  let g:oscyank_term = 'kitty'
  let g:clipboard = {
    \ 'name': 'osc52',
    \ 'copy': {
    \   '+': {lines, regtype -> OSCYankString(join(lines, "\n"))},
    \   '*': {lines, regtype -> OSCYankString(join(lines, "\n"))},
    \ },
    \ 'paste': {
    \   '+': {-> [split(getreg(''), '\n'), getregtype('')]},
    \   '*': {-> [split(getreg(''), '\n'), getregtype('')]},
    \ },
    \ }
'''

[[plugins]]
repo = 'lambdalisue/gin.vim'
depends = 'denops.vim'

[[plugins]]
repo = 'junegunn/gv.vim'

# [[plugins]]
# repo = 'cocopon/pgmnt.vim'

# [[plugins]]
# repo = 'yash268925/iceberg.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_add = '''
  call LoadSubscript('init/ddc.vim')
'''

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'LumaKernel/ddc-file'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
depends = ['nvim-lspconfig', 'denops.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline'
depends = ['denops.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-cmdline-history'
depends = ['denops.vim']
on_source = 'ddc.vim'

[[plugins]]
repo = 'tani/ddc-fuzzy'
on_source = 'ddc.vim'

[[plugins]]
repo = 'vim-scripts/Decho'

[[plugins]]
repo = 'lambdalisue/suda.vim'
hook_add = '''
  let g:suda_smart_edit = 1
'''
