local jdtls = require('jdtls')

local bufname = vim.api.nvim_buf_get_name(0)

local root_dir = require('jdtls.setup').find_root({
  '.git',
  'gradlew',
  'mvnw',
  'settings.gradle',
  'settings.gradle.kts',
})
if not root_dir or root_dir == '' then
  return
end

local project_name = vim.fn.fnamemodify(root_dir, ':p:h:t')

-- Android Gradle Plugin(com.android.application/library)を使うモジュールは、
-- Eclipse BuildshipがそのソースセットをEclipseProjectモデルとして解決できず、
-- 同期のたびにソースフォルダなしのclasspathで上書きしてしまう(既知の構造的制約。
-- Gradle自体のビルドやJVMバージョンの問題ではない)。
--
-- かつては「invisible project」方式(srcをworkspace rootにしてreferencedLibrariesで
-- 依存を与える)にフォールバックしていたが、jdt.lsのInvisibleProjectImporterは
-- 推定ソースディレクトリ(src/main/java)の"src"セグメントの親にbuild.gradleがあると
-- isPartOfMatureProject判定でinvisible project化を拒否するため、AGPモジュールでは
-- 構造的に成立しない(ファイルはデフォルトプロジェクトにスタンドアロンでリンクされ
-- 構文チェックのみになり、ホバー・他ファイルへの定義ジャンプが効かない)。
--
-- 現在は、モジュール直下に静的なEclipseプロジェクト(.project/.classpath/.settings)を
-- 生成し、Gradle/Mavenインポートを無効化してEclipseProjectImporterに読ませる方式。
-- Buildshipを通らないので同期による上書きも起きない。
--
-- 依存JARの一覧は ~/.cache/nvim/jdtls-libs/<project>-<module>.txt に事前生成しておく
-- (生成方法は ~/.config/nvim/jdtls/android-libs.init.gradle のコメントを参照)。
-- build.gradleの依存が変わったらこのキャッシュを再生成すれば、次回起動時に
-- .classpathも作り直される。
local function find_android_module_dir(file_path, base)
  local dir = vim.fn.fnamemodify(file_path, ':h')
  while #dir > #base do
    local is_gradle_module = vim.fn.filereadable(dir .. '/build.gradle') == 1
      or vim.fn.filereadable(dir .. '/build.gradle.kts') == 1
    if is_gradle_module then
      if vim.fn.filereadable(dir .. '/src/main/AndroidManifest.xml') == 1 then
        return dir
      end
      return nil
    end
    local parent = vim.fn.fnamemodify(dir, ':h')
    if parent == dir then
      break
    end
    dir = parent
  end
  return nil
end

local android_module_dir = find_android_module_dir(bufname, root_dir)

if android_module_dir then
  local module_name = vim.fn.fnamemodify(android_module_dir, ':t')
  local libs_cache = vim.fn.stdpath('cache') .. '/jdtls-libs/' .. project_name .. '-' .. module_name .. '.txt'

  if vim.fn.filereadable(libs_cache) == 1 then
    local project_file = android_module_dir .. '/.project'
    local classpath_file = android_module_dir .. '/.classpath'

    -- .classpathがlibsキャッシュより古い(または存在しない)場合のみ再生成する。
    if
      vim.fn.filereadable(project_file) == 0
      or vim.fn.filereadable(classpath_file) == 0
      or vim.fn.getftime(classpath_file) < vim.fn.getftime(libs_cache)
    then
      vim.fn.writefile({
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<projectDescription>',
        '\t<name>' .. project_name .. '-' .. module_name .. '</name>',
        '\t<comment>generated by ftplugin/java.lua (do not edit by hand)</comment>',
        '\t<projects></projects>',
        '\t<buildSpec>',
        '\t\t<buildCommand>',
        '\t\t\t<name>org.eclipse.jdt.core.javabuilder</name>',
        '\t\t\t<arguments></arguments>',
        '\t\t</buildCommand>',
        '\t</buildSpec>',
        '\t<natures>',
        '\t\t<nature>org.eclipse.jdt.core.javanature</nature>',
        '\t</natures>',
        '</projectDescription>',
      }, project_file)

      -- テストソース(test/androidTest)はコンパイルクラスパスに依存が無く
      -- エラーだらけになるだけなので、mainのみをソースフォルダにする。
      -- android.jarがjava.*を提供するため、JREコンテナはあえて入れない
      -- (入れるとjava.*がJDK側に解決されandroid.jarと食い違う)。
      local classpath = {
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<classpath>',
        '\t<classpathentry kind="src" path="src/main/java"/>',
      }
      for _, line in ipairs(vim.fn.readfile(libs_cache)) do
        if line ~= '' then
          table.insert(classpath, '\t<classpathentry kind="lib" path="' .. line .. '"/>')
        end
      end
      table.insert(classpath, '\t<classpathentry kind="output" path="bin"/>')
      table.insert(classpath, '</classpath>')
      vim.fn.writefile(classpath, classpath_file)

      -- コンパイラ準拠レベルを明示する。未指定だとjdtls起動JVM(最新)基準になり、
      -- android.jar(1.8想定)との組み合わせで誤診断が出うる。AGPのcompileOptions
      -- デフォルトに合わせて1.8固定。
      vim.fn.mkdir(android_module_dir .. '/.settings', 'p')
      vim.fn.writefile({
        'eclipse.preferences.version=1',
        'org.eclipse.jdt.core.compiler.codegen.targetPlatform=1.8',
        'org.eclipse.jdt.core.compiler.compliance=1.8',
        'org.eclipse.jdt.core.compiler.source=1.8',
      }, android_module_dir .. '/.settings/org.eclipse.jdt.core.prefs')
    end

    local workspace_dir = vim.fn.stdpath('cache') .. '/jdtls-workspace/' .. project_name .. '-' .. module_name

    local android_config = {
      cmd = { 'jdtls', '-data', workspace_dir },
      root_dir = android_module_dir,
      settings = {
        java = {
          import = {
            gradle = { enabled = false },
            maven = { enabled = false },
          },
        },
      },
      init_options = {
        bundles = {},
        extendedClientCapabilities = jdtls.extendedClientCapabilities,
      },
    }
    -- settingsはworkspace/didChangeConfigurationとしてinitialize完了"後"に送られるため、
    -- それだけだと起動直後のインポートでGradleProjectImporter(Buildship)が先に走って
    -- しまう。initializationOptions.settingsとして渡すことでinitialize時点から
    -- Gradle/Mavenインポート無効を効かせ、EclipseProjectImporterに.projectを拾わせる。
    android_config.init_options.settings = android_config.settings

    jdtls.start_or_attach(android_config)
    return
  end

  vim.notify(
    'jdtls: Androidモジュール(' .. module_name .. ')用の依存関係キャッシュが見つかりません: ' .. libs_cache,
    vim.log.levels.WARN
  )
end

-- 通常のGradle/Mavenプロジェクト(AGP以外)はこれまで通りBuildship経由でインポートする。
local workspace_dir = vim.fn.stdpath('cache') .. '/jdtls-workspace/' .. project_name

-- gradle.propertiesでorg.gradle.java.homeが明示されているプロジェクトでは、
-- Buildshipが使うGradle Tooling API接続先のJDKもそれに合わせる。
-- 未指定ならシステムデフォルトのままにして他プロジェクトに影響させない。
-- (指定なしだとjdtls起動元JVMがそのままToolingAPI接続に使われ、
--  そのJVMをGradle側がまだサポートしていないと同期が失敗することがある。
--  ただしjdtls本体の起動JVM(cmd_env)自体は変えない。jdtls自体はJava21+を
--  要求するため、Gradleビルド用の古めのJDKで上書きするとjdtls起動自体が
--  失敗する。あくまでGradle Tooling API接続先だけを settings 経由で指定する)
local gradle_java_home = nil
local gradle_properties = io.open(root_dir .. '/gradle.properties', 'r')
if gradle_properties then
  for line in gradle_properties:lines() do
    local value = line:match('^%s*org%.gradle%.java%.home%s*=%s*(.-)%s*$')
    if value then
      gradle_java_home = value
    end
  end
  gradle_properties:close()
end

local jdtls_config = {
  cmd = { 'jdtls', '-data', workspace_dir },
  root_dir = root_dir,
  settings = {
    java = {
      import = {
        gradle = {
          enabled = true,
          wrapper = { enabled = true },
        },
      },
      configuration = {
        updateBuildConfiguration = 'automatic',
      },
    },
  },
  init_options = {
    bundles = {},
    extendedClientCapabilities = jdtls.extendedClientCapabilities,
  },
}

if gradle_java_home then
  jdtls_config.settings.java.import.gradle.java = { home = gradle_java_home }
end

jdtls.start_or_attach(jdtls_config)
